### ISSUE TITLE
反馈2个问题

### ISSUE THREAD

**Issue by kinghom** [woxingxiao/SlidingUpPanelLayout#2]
1、4.4可以运行，效果有点小瑕疵。
2、在信用卡的界面，如果先点击第一张卡，再点第二张卡，效果是第一张下来，第二张上去，属于正常效果；如果先点第二张卡，再点第一张卡，效果是第二张卡下来，第一张却没有上去，个人觉得第一张卡应该上去才比较符合用户操作。

**Comment by woxingxiao** [comment]
1. demo中的卡片是`CardView`，5.0以下样式可能会难看。demo仅作演示。
2. 实际上，`Panel`展开时是将父控件`SlidingUpPanelLayout`充满的（参看天气demo），银行卡demo下部是透明的，但被点击的还是当前View，它下层的卡片接收不了事件的。demo仅作演示。
