### ISSUE TITLE
你好，有时间帮我看看这个吗

### ISSUE THREAD

**Issue by Theoneee** [woxingxiao/SlidingUpPanelLayout#9]
![1](https://user-images.githubusercontent.com/32156330/50416918-1132ca00-085e-11e9-9838-7fab143c9322.png)

我是放在Fragment里面的，但是最下面的那一块的高度感觉不是从Fragment的底边开始的。怎么让卡片一开始不是打开的啊。。。

**Comment by Theoneee** [comment]
还有就是能不能让卡片的排列从添加事件 下面开始，不要从底部开始。。

**Comment by Theoneee** [comment]
解决了。感谢开源~~  辛苦了~

**Comment by dhavaljivani** [comment]
Can you please tell me what is the solution for this issue?
您能否告诉我该问题的解决方案是什么？
